security:
    password_hashers:
        App\Entity\User: 'auto' 
    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/article/add, roles: ROLE_ADMIN }
        - { path: ^/article/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/article/\d+/delete, roles: ROLE_ADMIN }
        - { path: ^/comment/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/comment/\d+/delete, roles: ROLE_ADMIN }
        - { path: ^/comment/add, roles: ROLE_USER }
